-- 테이블 DROP
DROP TABLE ATTENDANCE;
DROP TABLE BUYPRODUCT;
DROP TABLE PRODUCTPHOTO;
DROP TABLE PRODUCTBUY;
DROP TABLE PRODUCT;
DROP TABLE PRODUCTCATEGORY;
DROP TABLE REPLY;
DROP TABLE QNA;
DROP TABLE BOARD;
DROP TABLE POINT;
DROP TABLE RESULT;
DROP TABLE USER_INFO;
DROP TABLE ANSWER;
DROP TABLE QUESTION;
DROP TABLE QUESTION_TYPE;
DROP TABLE SURVEY;
DROP TABLE SURVEY_TYPE;
DROP TABLE SURVEY_TARGET;
drop table qna_type;


-- 시퀀스 드랍
DROP SEQUENCE SEQ_SURVEY_TARGET;
DROP SEQUENCE SEQ_ATTENDANCE;
DROP SEQUENCE SEQ_PRODUCT;
DROP SEQUENCE SEQ_PRODUCTCATEGORY;
DROP SEQUENCE SEQ_BUYPRODUCT;
DROP SEQUENCE SEQ_PRODUCTPHOTO;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_REPLY;
DROP SEQUENCE SEQ_QNA;
DROP SEQUENCE SEQ_POINT;
DROP SEQUENCE SEQ_SURVEY;
DROP SEQUENCE SEQ_QUESTION;
DROP SEQUENCE SEQ_ANSWER;
DROP SEQUENCE SEQ_RESULT;

-- user 테이블 생성
CREATE TABLE USER_INFO(
	 USERID VARCHAR(20) NOT NULL,
	 USERPWD VARCHAR(255) NOT NULL,
	 USERNAME VARCHAR(20) NOT NULL,
	 AGE NUMBER(5),
	 GENDER VARCHAR(6),
     EMAIL 	VARCHAR(50),
	 PHONE 	VARCHAR(11),
	 ADDRESS VARCHAR(100),
	 RECOMMEND_ID VARCHAR(20),
	 SURVEYCOUNT NUMBER(38) DEFAULT 0,
	 VISITCOUNT NUMBER(38) DEFAULT 0,
	 USERTYPE NUMBER(1) DEFAULT '2',
	 STATUS VARCHAR(1) DEFAULT 'N',     
	 FINAL_EDUCATION VARCHAR(50),
	 JOB VARCHAR(20),
	 INCOME VARCHAR(50),
	 LIVING_TYPE VARCHAR(10),
	 HOUSE_TYPE VARCHAR(20),
	 RELIGION VARCHAR(10),
	 MARITAL_STATUS VARCHAR(10),
	 LIVING_WITH VARCHAR(15),
	 ARMY_GO VARCHAR(10), 
	 INTEREST VARCHAR(300),
     PWDDATE DATE DEFAULT SYSDATE,
     JOINDATE DATE DEFAULT SYSDATE,
     POINT NUMBER(38) DEFAULT 0,
    CONSTRAINT USER_INFO_PK PRIMARY KEY (USERID)
);

-- 공지사항 및 이벤트 테이블
CREATE TABLE BOARD (
BNUM	NUMBER(38) NOT NULL,
BWRITER	VARCHAR2(20),
BWNAME	VARCHAR2(20),
BTITLE	VARCHAR2(100),
BCONTENT	NVARCHAR2(2000),
BCREATEDT	DATE,
BTYPE	VARCHAR2(1),
BSTATUS	VARCHAR2(1),
BCOUNT	NUMBER(3),
CONSTRAINT BOARD_PK PRIMARY KEY(BNUM),
CONSTRAINT BOARD_FK FOREIGN KEY(BWRITER) REFERENCES USER_INFO(USERID)
);

CREATE SEQUENCE SEQ_BOARD;

-- 덧글 테이블
CREATE TABLE REPLY(
	 REPLYNUM NUMBER(38) NOT NULL,
	 BNUM NUMBER(38) NOT NULL,
	 REPLYID VARCHAR(20) NOT NULL,
	 REPLYTEXT LONG,
	 REPLYDATE DATE DEFAULT SYSDATE,
	 REPLYSTATUS VARCHAR(1) DEFAULT 'N',
     CONSTRAINT REPLY_PK PRIMARY KEY(REPLYNUM),
     CONSTRAINT REPLY_CNUM_FK FOREIGN KEY(BNUM) REFERENCES BOARD(BNUM),
     CONSTRAINT REPLY_REPLYID_FK FOREIGN KEY(REPLYID) REFERENCES USER_INFO(USERID)
);
 
CREATE SEQUENCE SEQ_REPLY;

-- QnA 테이블

	 CREATE TABLE QNA(
	 QNANUM NUMBER(38) NOT NULL,
	 USERID VARCHAR(20) NOT NULL,
	 QNATITLE VARCHAR(100),
	 QNACONTENT NVARCHAR2(2000),
	 QNATYPE VARCHAR(1),
	 ACONTENT NVARCHAR2(2000),
     CONSTRAINT QNA_PK PRIMARY KEY(QNANUM),
     CONSTRAINT QNA_FK FOREIGN KEY(USERID) REFERENCES USER_INFO(USERID)  ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_QNA;

-- point 테이블
CREATE TABLE POINT(
	 PNUM NUMBER(38) NOT NULL,
     USERID VARCHAR(20) NOT NULL,
	 POINT NUMBER(38),
	 PDATE DATE,
	 PCONTENT VARCHAR(100),
     CONSTRAINT POINT_PK PRIMARY KEY(PNUM),
     CONSTRAINT POINT_FK FOREIGN KEY(USERID) REFERENCES USER_INFO(USERID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_POINT;

-- 설문타입 테이블
CREATE TABLE SURVEY_TYPE(
	 STYPE VARCHAR(20) NOT NULL,
	 STNAME VARCHAR(20),
      CONSTRAINT SURVEY_TYPE_PK PRIMARY KEY(STYPE)
);

-- survey 테이블
CREATE TABLE SURVEY(
	 SNUM NUMBER(38) NOT NULL,
	 STYPE VARCHAR(20) NOT NULL,
	 STITLE VARCHAR(100),
	 SSTARTDT DATE,
	 SENDDT DATE,
	 SCOUNT NUMBER(38),
	 SPOINT NUMBER(38),   -- 설문조사 포인트
	 QCOUNT NUMBER(38),
	 ACOUNT NUMBER(38),
	 SSTATUS VARCHAR(1),
	 STARGET VARCHAR(200),
     SCREATEDT DATE, -- 설문만든날짜
     SUSERID VARCHAR(20), -- 설문등록 아이디
     SANSWERID VARCHAR2(500),
     CONSTRAINT SURVEY_PK PRIMARY KEY(SNUM),
     CONSTRAINT SURVEY_FK FOREIGN KEY(STYPE) REFERENCES SURVEY_TYPE(STYPE) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_SURVEY;

-- 질문 타입 테이블
CREATE TABLE QUESTION_TYPE(
	 QTYPE VARCHAR(255)	NOT NULL,
	 QTNAME VARCHAR(255),
     CONSTRAINT QUESTION_TYPE_PK PRIMARY KEY(QTYPE)
);

-- 질문 테이블
CREATE TABLE QUESTION(
	 QNUM NUMBER(38) NOT NULL,
	 SNUM NUMBER(38) NOT NULL,
	 QTYPE VARCHAR(20) NOT NULL,
	 QTITLE VARCHAR(100),
     CONSTRAINT QUESTION_PK PRIMARY KEY(QNUM),
     CONSTRAINT QUESTION_SNUM_FK FOREIGN KEY(SNUM) REFERENCES SURVEY(SNUM) ON DELETE CASCADE,
     CONSTRAINT QUESTION_QTYPE_FK FOREIGN KEY(QTYPE) REFERENCES QUESTION_TYPE(QTYPE) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_QUESTION;

-- 항목 테이블
CREATE TABLE ANSWER(
	 ANUM NUMBER(38) NOT NULL,
	 QNUM NUMBER(38) NOT NULL,
	 ACONTENT VARCHAR(200),
	 ANSWERCOUNT NUMBER(38) DEFAULT 0,
     CONSTRAINT ANSWER_PK PRIMARY KEY(ANUM),
     CONSTRAINT ANSWER_FK FOREIGN KEY(QNUM) REFERENCES QUESTION(QNUM) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_ANSWER;

-- 결과 테이블
CREATE TABLE RESULT(
	 RNUM NUMBER(38)NOT NULL,
	 ANUM NUMBER(38)NOT NULL,
     QNUM NUMBER(38) NOT NULL,
     RUSERID VARCHAR(20) NOT NULL,
	 RTEXT VARCHAR(20),  -- 단답&서술형 답안 컬럼
	 RDATE DATE DEFAULT SYSDATE, -- 회원 응답 날짜
     CONSTRAINT RESULT_ANUM_FK FOREIGN KEY(ANUM) REFERENCES ANSWER(ANUM) ON DELETE CASCADE,
     CONSTRAINT RESULT_USERID_FK FOREIGN KEY(RUSERID) REFERENCES USER_INFO(USERID) ON DELETE CASCADE
);


CREATE SEQUENCE SEQ_RESULT;

CREATE TABLE ATTENDANCE(
    ATTNUM NUMBER(38) NOT NULL,
    USERID VARCHAR(20) NOT NULL,
    ATTPOINT NUMBER(38),    -- 출석 체크 했을 때 얻는 포인트
    ATTCOUNT NUMBER(38),    -- 총 출석한 수
    ATTDATE DATE,           -- 출석체크한 날
    CONSTRAINT ATTENDANCE_PK PRIMARY KEY(ATTNUM),
    CONSTRAINT ATTENDANCE_FK FOREIGN KEY(USERID) REFERENCES USER_INFO(USERID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_ATTENDANCE;


-- 제품 카테고리 
CREATE TABLE PRODUCTCATEGORY(
    CATEGORYID	VARCHAR2(10),
    CATEGORYNAME VARCHAR2(20),
    CONSTRAINT PRODUCTCATEGORY_PK PRIMARY KEY(CATEGORYID)
);

CREATE SEQUENCE SEQ_PRODUCTCATEGORY;

-- 제품 테이블
CREATE TABLE PRODUCT(
    PRONUM	NUMBER(38) NOT NULL,
    CATEGORYID	VARCHAR2(10),
    PRONAME	VARCHAR2(255),
    PPRICE	NUMBER(38),
    PROTEXT	VARCHAR2(255),
CONSTRAINT PRODUCT_PK PRIMARY KEY(PRONUM),
CONSTRAINT PRODUCT_FK FOREIGN KEY(CATEGORYID) REFERENCES PRODUCTCATEGORY(CATEGORYID)
);

CREATE TABLE qnatype (
    QNATYPE   VARCHAR2(1),
    TYPENAME VARCHAR2(25)
);

INSERT INTO qnatype VALUES('A','설문결제');
INSERT INTO qnatype VALUES('S','설문조사');
INSERT INTO qnatype VALUES('P','포인트교환');
INSERT INTO qnatype VALUES('R','추천인');
INSERT INTO qnatype VALUES('E','기타');
INSERT INTO qnatype VALUES('L','회원가입/로그인');


CREATE SEQUENCE SEQ_PRODUCT;


-- 제품을 구매한 사람의 테이블
CREATE TABLE PRODUCTBUY(
    BNUM NUMBER(38) NOT NULL,
    PRONUM NUMBER(38) NOT NULL,
    USERID VARCHAR(20) NOT NULL,
    PRICE NUMBER(38),
    BUYDATE DATE,
    CONSTRAINT PRODUCTBUY_PF PRIMARY KEY(BNUM),
    CONSTRAINT PRODUCTBUY_FK1 FOREIGN KEY(PRONUM) REFERENCES PRODUCT(PRONUM),
    CONSTRAINT PRODUCTBUY_FK2 FOREIGN KEY(USERID) REFERENCES USER_INFO(USERID)
);

CREATE SEQUENCE SEQ_BUYPRODUCT;

-- 제품 사진 테이블
CREATE TABLE PRODUCTPHOTO(
   PHOTONUM NUMBER(38) NOT NULL,
   PRONUM NUMBER(38) NOT NULL,
   PHOTONAME VARCHAR(255),
   PHOTOPATH VARCHAR(255),
    CONSTRAINT PRODUCTPHOTO_PK PRIMARY KEY(PHOTONUM),
    CONSTRAINT PRODUCTPHOTO_FK FOREIGN KEY(PRONUM) REFERENCES PRODUCT(PRONUM) ON DELETE CASCADE
);
ALTER TABLE productphoto ADD(PHOTOCHANGENAME VARCHAR2(255));
CREATE SEQUENCE SEQ_PRODUCTPHOTO;

CREATE TABLE SURVEY_TARGET(
    SVNUM NUMBER(38),
    SNUM NUMBER(38),
    TARGETTYPE VARCHAR(50),
    TARGETDETAIL VARCHAR(200)
);

CREATE SEQUENCE SEQ_SURVEY_TARGET;

ALTER TABLE QUESTION
DROP CONSTRAINT QUESTION_SNUM_FK;

ALTER TABLE QUESTION
ADD CONSTRAINT QUESTION_SNUM_FK FOREIGN KEY(SNUM) REFERENCES SURVEY(SNUM) ON DELETE CASCADE;


INSERT INTO QUESTION_TYPE VALUES('객관식',NULL);
INSERT INTO QUESTION_TYPE VALUES('주관식',NULL);
INSERT INTO QUESTION_TYPE VALUES('랭킹',NULL);



INSERT INTO SURVEY_TYPE
VALUES('스포츠','스포츠');
INSERT INTO SURVEY_TYPE
VALUES('음식','음식');
INSERT INTO SURVEY_TYPE
VALUES('여행','여행');
INSERT INTO SURVEY_TYPE
VALUES('게임','게임');
INSERT INTO SURVEY_TYPE
VALUES('과학','과학');
INSERT INTO SURVEY_TYPE
VALUES('패션','패션');
INSERT INTO SURVEY_TYPE
VALUES('IT','IT');
INSERT INTO SURVEY_TYPE
VALUES('자동차','자동차');
INSERT INTO SURVEY_TYPE
VALUES('사회이슈','사회이슈');
INSERT INTO SURVEY_TYPE
VALUES('연예인','연예인');
INSERT INTO SURVEY_TYPE
VALUES('육아','육아');
INSERT INTO SURVEY_TYPE
VALUES('취업','취업');
INSERT INTO SURVEY_TYPE
VALUES('교육','교육');
INSERT INTO SURVEY_TYPE
VALUES('가족','가족');
INSERT INTO SURVEY_TYPE
VALUES('문화생활','문화생활');
INSERT INTO SURVEY_TYPE
VALUES('애견','애견');

INSERT INTO PRODUCTCATEGORY VALUES('p01', '베이커리');
INSERT INTO PRODUCTCATEGORY VALUES('p02', '카페');
INSERT INTO PRODUCTCATEGORY VALUES('p03', '패스트푸드');
INSERT INTO PRODUCTCATEGORY VALUES('p04', '편의점');
INSERT INTO PRODUCTCATEGORY VALUES('p05', '외식');
INSERT INTO PRODUCTCATEGORY VALUES('p06', '상품권');
INSERT INTO PRODUCTCATEGORY VALUES('p07', '현금');



INSERT INTO USER_INFO(USERID, USERPWD, USERNAME,USERTYPE) VALUES('admin', '1ARVn2Auq2/WAqx2gNrL+q3RNjAzXpUfCXrzkA6d4Xa22yhRLy4AC50E+6UTPoscbo31nbOoq51gvkuXzJ6B2w==', '관리자',1);
ALTER TABLE USER_INFO ADD (PWDVISIBLE VARCHAR2(255));
UPDATE USER_INFO SET PWDVISIBLE = 'asdqwe123!@#';
COMMIT;

COMMIT;