DROP TABLE USER_INFO2;
DROP TABLE POINT;
DROP TABLE COMMENTS;
DROP TABLE SURVEY_QUESTION_ANSWER;
DROP TABLE RESULT;
DROP TABLE ANSWER;
DROP TABLE QNA_CUSTOMER;
DROP TABLE NOTICE;
DROP TABLE SURVEY;
DROP TABLE SURVEY_TYPE;
DROP TABLE QUESTION;
DROP TABLE USER_INFO1;

CREATE TABLE USER_INFO1 (
 USERID VARCHAR(20) NOT NULL,
 USERPWD VARCHAR(100) ,
 USERNAME VARCHAR(20) ,
 AGE NUMBER(10) ,
 ADDRESS VARCHAR(100) ,
 PHONE NUMBER(11) ,
 EMAIL VARCHAR(50) ,
 USERTYPE NUMBER(1)  DEFAULT 2,
 STATUS VARCHAR(1)  DEFAULT 'N'
);


CREATE TABLE USER_INFO2 (
 USERID VARCHAR(20) NOT NULL,
 FINAL_EDUCATION VARCHAR(50) ,
 JOB VARCHAR(20) ,
 INCOME_SELF VARCHAR(50) ,
 LIVING_TYPE VARCHAR(10) ,
 HOUSE_TYPE VARCHAR(10) ,
 MARITAL_STATUS VARCHAR(1) ,
 ARMY_GO VARCHAR(1) ,
 LIVING_WITH VARCHAR(1) ,
 RELIGION VARCHAR(10),
 INTEREST VARCHAR(300)
);


CREATE TABLE POINT (
 USERID VARCHAR(20) NOT NULL,
 POINT NUMBER(20) ,
 PLUSPOINT VARCHAR(100) ,
 PLUSPOINTDT DATE DEFAULT SYSDATE,
 MINUSPOINT VARCHAR(100) ,
 MINUSPOINTDT DATE DEFAULT SYSDATE
);


CREATE TABLE NOTICE (
 NNUM NUMBER(38) NOT NULL,
 NWRITER VARCHAR(100) NOT NULL,
 NTITLE VARCHAR(100) ,
 NCONTENT VARCHAR(500) ,
 NCREATEDT DATE DEFAULT SYSDATE,
 NUPDATEDT DATE DEFAULT SYSDATE,
 NTYPE VARCHAR(1) ,
 NSTATUS VARCHAR(1)  DEFAULT 'N'
);


CREATE TABLE COMMENTS (
 CNUM NUMBER(38) NOT NULL,
 NNUM NUMBER(38) NOT NULL,
 CWRITER VARCHAR(100) NOT NULL,
 CCONTENT VARCHAR(150) ,
 CCREATEDT DATE DEFAULT SYSDATE,
 CUPDATEDT DATE DEFAULT SYSDATE ,
 CSTATUS VARCHAR(255)  DEFAULT 'N'
);


CREATE TABLE SURVEY (
 SNUM NUMBER(10) NOT NULL,
 STYPE VARCHAR(10) NOT NULL,
 STITLE VARCHAR(50) ,
 SSTARTDT DATE DEFAULT SYSDATE,
 SENDDT DATE,
 SCOUNT NUMBER(10),
 SSTATUS VARCHAR(1)  DEFAULT 'N',
 STARGET VARCHAR(100),
 QCOUNT NUMBER(10) NOT NULL
);


CREATE TABLE QUESTION (
 QNUM NUMBER(10) NOT NULL,
 QTITLE VARCHAR(50) ,
 QTYPE VARCHAR(5) 
);


CREATE TABLE ANSWER (
 ANUM NUMBER(10) NOT NULL,
 ANSWER VARCHAR(5) 
);


CREATE TABLE RESULT (
 USERID VARCHAR(20) NOT NULL,
 SNUM NUMBER(10) NOT NULL,
 QNUM NUMBER(10) NOT NULL,
 ANUM NUMBER(10) NOT NULL,
 OTHER_ANSWER VARCHAR(200) 
);


CREATE TABLE SURVEY_QUESTION_ANSWER (
 QNUM NUMBER(10) NOT NULL,
 SNUM NUMBER(10) NOT NULL,
 ANUM NUMBER(10) NOT NULL
);


CREATE TABLE QNA_CUSTOMER (
 QNANUM NUMBER(38) NOT NULL,
 USERID VARCHAR(20) NOT NULL,
 QNATITLE VARCHAR(50) ,
 QNACONTENT VARCHAR(500) ,
 QNATYPE VARCHAR(1) ,
 ACONTENT VARCHAR(500) 
);



CREATE TABLE SURVEY_TYPE (
 STYPE VARCHAR(10) NOT NULL,
 STNAME VARCHAR(10) ,
 SCODE VARCHAR(10) 
);


ALTER TABLE USER_INFO1 ADD CONSTRAINT PK_USER PRIMARY KEY(
	USERID
);

ALTER TABLE USER_INFO2 ADD CONSTRAINT PK_USER_INFO2 PRIMARY KEY(
	USERID
);

ALTER TABLE POINT ADD CONSTRAINT PK_POINT PRIMARY KEY(
	USERID
);

ALTER TABLE NOTICE ADD CONSTRAINT PK_NOTICE PRIMARY KEY(
	NNUM
);

ALTER TABLE COMMENTS ADD CONSTRAINT PK_COMMENTS PRIMARY KEY(
	CNUM,
	NNUM,
	CWRITER
);

ALTER TABLE SURVEY ADD CONSTRAINT PK_SURVEY PRIMARY KEY(
	SNUM
);

ALTER TABLE QUESTION ADD CONSTRAINT PK_QUESTION PRIMARY KEY(
	QNUM
);

ALTER TABLE ANSWER ADD CONSTRAINT PK_ANSWER PRIMARY KEY(
	ANUM
);

ALTER TABLE RESULT ADD CONSTRAINT PK_RESULT PRIMARY KEY(
	USERID,
	SNUM,
	QNUM,
	ANUM
);

ALTER TABLE SURVEY_QUESTION_ANSWER ADD CONSTRAINT PK_SURVEY_QUESTION_ANSWER PRIMARY KEY(
	QNUM,
	SNUM,
	ANUM
);

ALTER TABLE QNA_CUSTOMER ADD CONSTRAINT PK_QNA_CUSTOMER PRIMARY KEY(
	QNANUM,
	USERID
);

ALTER TABLE SURVEY_TYPE ADD CONSTRAINT PK_SURVEY_TYPE PRIMARY KEY(
	STYPE
);

ALTER TABLE USER_INFO2 ADD CONSTRAINT FK_USER_TO_USER_INFO2_1 FOREIGN KEY(
	USERID
)
REFERENCES USER_INFO1 (
	USERID
);

ALTER TABLE POINT ADD CONSTRAINT FK_USER_TO_POINT_1 FOREIGN KEY(
	USERID
)
REFERENCES USER_INFO1 (
	USERID
);

ALTER TABLE NOTICE ADD CONSTRAINT FK_USER_TO_NOTICE_1 FOREIGN KEY(
	NWRITER
)
REFERENCES USER_INFO1 (
	USERID
);

ALTER TABLE COMMENTS ADD CONSTRAINT FK_NOTICE_TO_COMMENTS_1 FOREIGN KEY(
	NNUM
)
REFERENCES NOTICE (
	NNUM
);

ALTER TABLE COMMENTS ADD CONSTRAINT FK_USER_TO_COMMENTS_1 FOREIGN KEY(
	CWRITER
)
REFERENCES USER_INFO1 (
	USERID
);

ALTER TABLE SURVEY ADD CONSTRAINT FK_SURVEY_CATEGORY_TO_SURVEY_1 FOREIGN KEY(
	STYPE
)
REFERENCES SURVEY_TYPE (
	STYPE
);

ALTER TABLE RESULT ADD CONSTRAINT FK_USER_TO_RESULT_1 FOREIGN KEY(
	USERID
)
REFERENCES USER_INFO1 (
	USERID
);

ALTER TABLE RESULT ADD CONSTRAINT FK_SURVEY_TO_RESULT_1 FOREIGN KEY(
	SNUM
)
REFERENCES SURVEY (
	SNUM
);

ALTER TABLE RESULT ADD CONSTRAINT FK_QUESTION_TO_RESULT_1 FOREIGN KEY(
	QNUM
)
REFERENCES QUESTION (
	QNUM
);

ALTER TABLE RESULT ADD CONSTRAINT FK_ANSWER_TO_RESULT_1 FOREIGN KEY(
	ANUM
)
REFERENCES ANSWER (
	ANUM
);

ALTER TABLE SURVEY_QUESTION_ANSWER ADD CONSTRAINT FK_QUESTION_ANSWER_1 FOREIGN KEY(
	QNUM
)
REFERENCES QUESTION (
	QNUM
);

ALTER TABLE SURVEY_QUESTION_ANSWER ADD CONSTRAINT FK_SURVEY_ANSWER_1 FOREIGN KEY(
	SNUM
)
REFERENCES SURVEY (
	SNUM
);

ALTER TABLE SURVEY_QUESTION_ANSWER ADD CONSTRAINT FK_ANSWER_ANSWER_1 FOREIGN KEY(
	ANUM
)
REFERENCES ANSWER (
	ANUM
);

ALTER TABLE QNA_CUSTOMER ADD CONSTRAINT FK_USER_TO_QNA_CUSTOMER_1 FOREIGN KEY(
	USERID
)
REFERENCES USER_INFO1 (
	USERID
);

